In [3]:
import numpy as np
import pandas as pd

In [5]:
latlong=pd.read_csv("/content/district wise centroids.csv")
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [6]:
latlong.shape

(594, 4)

In [9]:
latlong.isnull().sum() # check the duplicate

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [10]:
latlong.duplicated().sum()

np.int64(0)

In [12]:
census=pd.read_csv("/content/india-districts-census-2011.csv")
census

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,2316,4309,1370,838,2208,576,978,1554,1446,10027
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1063,2408,665,340,1005,246,483,729,341,4890
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,685,1895,212,134,346,70,120,190,84,3151
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,685,1895,212,134,346,70,120,190,84,3151
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1371,3020,649,368,1017,265,497,762,376,5782

In [16]:
cols=["District code","District name","Population","Male","Female","Literate","Households_with_Internet"]

In [18]:
census=census[cols]

In [19]:
census

,District code,District name,Population,Male,Female,Literate,Households_with_Internet
0,1,Kupwara,870354,474190,396164,439654,762
1,2,Badgam,753745,398041,355704,335649,1999
2,3,Leh(Ladakh),133487,78971,54516,93770,574
3,4,Kargil,140802,77785,63017,86236,235
4,5,Punch,476835,251899,224936,261724,346
...,...,...,...,...,...,...,...
635,636,Mahe,41816,19143,22673,36470,574
636,637,Karaikal,200222,97809,102413,154916,1868
637,638,Nicobars,36842,20727,16115,25332,57
638,639,North AND Middle Andaman,105597,54861,50736,78683,388
639,640,South Andaman,238142,127283,110859,190266,2789

In [24]:
final_df=latlong.merge(census,left_on="District name",right_on="District name")  #  matching column both table # drop(columns=["district_name"])

In [25]:
final_df

,District code_x,State name,District name,Population_x,Male_x,Female_x,Literate_x,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity,District code_y,Population_y,Male_y,Female_y,Literate_y,Households_with_Internet_y
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,10,84,15,1119,1,870354,474190,396164,439654,762
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,28,124,18,1066,2,753745,398041,355704,335649,1999
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,14,34,17,242,3,133487,78971,54516,93770,574
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,3,22,7,214,4,140802,77785,63017,86236,235
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,8,67,12,629,5,476835,251899,224936,261724,346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,978,1554,1446,10027,636,41816,19143,22673,36470,574
648,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,483,729,341,4890,637,200222,97809,102413,154916,1868
649,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,120,190,84,3151,638,36842,20727,16115,25332,57
650,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,120,190,84,3151,639,105597,54861,50736,78683,388
651,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,497,762,376,5782,640,238142,127283,110859,190266,2789

In [28]:
final_df["sex_ratio"]=round((final_df["Female_x"]/final_df["Male_x"])*100)

In [29]:
final_df

,District code_x,State name,District name,Population_x,Male_x,Female_x,Literate_x,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity,District code_y,Population_y,Male_y,Female_y,Literate_y,Households_with_Internet_y,sex_ratio
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,84,15,1119,1,870354,474190,396164,439654,762,84.0
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,124,18,1066,2,753745,398041,355704,335649,1999,89.0
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,34,17,242,3,133487,78971,54516,93770,574,69.0
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,22,7,214,4,140802,77785,63017,86236,235,81.0
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,67,12,629,5,476835,251899,224936,261724,346,89.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,1554,1446,10027,636,41816,19143,22673,36470,574,118.0
648,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,729,341,4890,637,200222,97809,102413,154916,1868,105.0
649,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,190,84,3151,638,36842,20727,16115,25332,57,78.0
650,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,190,84,3151,639,105597,54861,50736,78683,388,92.0
651,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,762,376,5782,640,238142,127283,110859,190266,2789,87.0

In [33]:
final_df["literacy_rate"]=round((final_df["Literate_x"]/final_df["Population_x"])*100)

In [47]:
final_df

,District code_x,State name,District name,Population_x,SC,Male_SC,Female_SC,ST,Male_ST,Female_ST,...,Power_Parity_Above_Rs_545000,Total_Power_Parity,District code_y,Population_y,Male_y,Female_y,Literate_y,Households_with_Internet_y,sex_ratio,literacy_rate
0,1,JAMMU AND KASHMIR,Kupwara,870354,1048,1046,2,70352,36913,33439,...,15,1119,1,870354,474190,396164,439654,762,84.0,51.0
1,2,JAMMU AND KASHMIR,Badgam,753745,368,343,25,23912,12383,11529,...,18,1066,2,753745,398041,355704,335649,1999,89.0,45.0
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,488,444,44,95857,47543,48314,...,17,242,3,133487,78971,54516,93770,574,69.0,70.0
3,4,JAMMU AND KASHMIR,Kargil,140802,18,12,6,122336,62652,59684,...,7,214,4,140802,77785,63017,86236,235,81.0,61.0
4,5,JAMMU AND KASHMIR,Punch,476835,556,406,150,176101,90274,85827,...,12,629,5,476835,251899,224936,261724,346,89.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,636,PONDICHERRY,Mahe,41816,144,77,67,0,0,0,...,1446,10027,636,41816,19143,22673,36470,574,118.0,87.0
648,637,PONDICHERRY,Karaikal,200222,35348,17206,18142,0,0,0,...,341,4890,637,200222,97809,102413,154916,1868,105.0,77.0
649,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,0,0,0,23681,12198,11483,...,84,3151,638,36842,20727,16115,25332,57,78.0,69.0
650,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,0,0,0,758,415,343,...,84,3151,639,105597,54861,50736,78683,388,92.0,75.0
651,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,0,0,0,4091,2118,1973,...,376,5782,640,238142,127283,110859,190266,2789,87.0,80.0

In [38]:
final_df.drop(columns=["Male_x","Female_x","Literate_x","Male_Literate","Female_Literate"],inplace=True)

In [39]:
final_df

,District code_x,State name,District name,Population_x,SC,Male_SC,Female_SC,ST,Male_ST,Female_ST,...,Power_Parity_Above_Rs_545000,Total_Power_Parity,District code_y,Population_y,Male_y,Female_y,Literate_y,Households_with_Internet_y,sex_ratio,literacy_rate
0,1,JAMMU AND KASHMIR,Kupwara,870354,1048,1046,2,70352,36913,33439,...,15,1119,1,870354,474190,396164,439654,762,84.0,51.0
1,2,JAMMU AND KASHMIR,Badgam,753745,368,343,25,23912,12383,11529,...,18,1066,2,753745,398041,355704,335649,1999,89.0,45.0
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,488,444,44,95857,47543,48314,...,17,242,3,133487,78971,54516,93770,574,69.0,70.0
3,4,JAMMU AND KASHMIR,Kargil,140802,18,12,6,122336,62652,59684,...,7,214,4,140802,77785,63017,86236,235,81.0,61.0
4,5,JAMMU AND KASHMIR,Punch,476835,556,406,150,176101,90274,85827,...,12,629,5,476835,251899,224936,261724,346,89.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,636,PONDICHERRY,Mahe,41816,144,77,67,0,0,0,...,1446,10027,636,41816,19143,22673,36470,574,118.0,87.0
648,637,PONDICHERRY,Karaikal,200222,35348,17206,18142,0,0,0,...,341,4890,637,200222,97809,102413,154916,1868,105.0,77.0
649,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,0,0,0,23681,12198,11483,...,84,3151,638,36842,20727,16115,25332,57,78.0,69.0
650,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,0,0,0,758,415,343,...,84,3151,639,105597,54861,50736,78683,388,92.0,75.0
651,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,0,0,0,4091,2118,1973,...,376,5782,640,238142,127283,110859,190266,2789,87.0,80.0

In [40]:
# export the data
final_df.to_csv("india.csv",index=False)

In [42]:
list_of_states=list(final_df["State name"].unique())
list_of_states

['JAMMU AND KASHMIR',
 'HIMACHAL PRADESH',
 'PUNJAB',
 'CHANDIGARH',
 'UTTARAKHAND',
 'HARYANA',
 'NCT OF DELHI',
 'RAJASTHAN',
 'UTTAR PRADESH',
 'BIHAR',
 'SIKKIM',
 'ARUNACHAL PRADESH',
 'NAGALAND',
 'MANIPUR',
 'MIZORAM',
 'TRIPURA',
 'MEGHALAYA',
 'ASSAM',
 'WEST BENGAL',
 'JHARKHAND',
 'ORISSA',
 'CHHATTISGARH',
 'MADHYA PRADESH',
 'GUJARAT',
 'DAMAN AND DIU',
 'DADRA AND NAGAR HAVELI',
 'MAHARASHTRA',
 'ANDHRA PRADESH',
 'KARNATAKA',
 'GOA',
 'LAKSHADWEEP',
 'KERALA',
 'TAMIL NADU',
 'PONDICHERRY',
 'ANDAMAN AND NICOBAR ISLANDS']

In [43]:
list_of_states.insert(0,"Overall India")  # insert meanse add on overall india first position
list_of_states

['Overall India',
 'JAMMU AND KASHMIR',
 'HIMACHAL PRADESH',
 'PUNJAB',
 'CHANDIGARH',
 'UTTARAKHAND',
 'HARYANA',
 'NCT OF DELHI',
 'RAJASTHAN',
 'UTTAR PRADESH',
 'BIHAR',
 'SIKKIM',
 'ARUNACHAL PRADESH',
 'NAGALAND',
 'MANIPUR',
 'MIZORAM',
 'TRIPURA',
 'MEGHALAYA',
 'ASSAM',
 'WEST BENGAL',
 'JHARKHAND',
 'ORISSA',
 'CHHATTISGARH',
 'MADHYA PRADESH',
 'GUJARAT',
 'DAMAN AND DIU',
 'DADRA AND NAGAR HAVELI',
 'MAHARASHTRA',
 'ANDHRA PRADESH',
 'KARNATAKA',
 'GOA',
 'LAKSHADWEEP',
 'KERALA',
 'TAMIL NADU',
 'PONDICHERRY',
 'ANDAMAN AND NICOBAR ISLANDS']

In [46]:
sorted(final_df.columns[5:])

['Age not stated',
 'Age_Group_0_29',
 'Age_Group_30_49',
 'Age_Group_50',
 'Agricultural_Workers',
 'Below_Primary_Education',
 'Buddhists',
 'Christians',
 'Condition_of_occupied_census_houses_Dilapidated_Households',
 'Cultivator_Workers',
 'District code_y',
 'Female_SC',
 'Female_ST',
 'Female_Workers',
 'Female_y',
 'Graduate_Education',
 'Having_bathing_facility_Total_Households',
 'Having_latrine_facility_within_the_premises_Total_Households',
 'Higher_Education',
 'Hindus',
 'Household_Workers',
 'Household_size_1_person_Households',
 'Household_size_1_to_2_persons',
 'Household_size_2_persons_Households',
 'Household_size_3_persons_Households',
 'Household_size_3_to_5_persons_Households',
 'Household_size_4_persons_Households',
 'Household_size_5_persons_Households',
 'Household_size_6_8_persons_Households',
 'Household_size_9_persons_and_above_Households',
 'Households',
 'Households_with_Bicycle',
 'Households_with_Car_Jeep_Van',
 'Households_with_Computer',
 'Households_with_Internet_x',
 'Households_with_Internet_y',
 'Households_with_Radio_Transistor',
 'Households_with_Scooter_Motorcycle_Moped',
 'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car',
 'Households_with_Telephone_Mobile_Phone',
 'Households_with_Telephone_Mobile_Phone_Both',
 'Households_with_Telephone_Mobile_Phone_Landline_only',
 'Households_with_Telephone_Mobile_Phone_Mobile_only',
 'Households_with_Television',
 'Households_with_separate_kitchen_Cooking_inside_house',
 'Housholds_with_Electric_Lighting',
 'Illiterate_Education',
 'Jains',
 'LPG_or_PNG_Households',
 'Literate_Education',
 'Literate_y',
 'Location_of_drinking_water_source_Away_Households',
 'Location_of_drinking_water_source_Near_the_premises_Households',
 'Location_of_drinking_water_source_Within_the_premises_Households',
 'Main_Workers',
 'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households',
 'Main_source_of_drinking_water_Other_sources_Households',
 'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households',
 'Main_source_of_drinking_water_River_Canal_Households',
 'Main_source_of_drinking_water_Spring_Households',
 'Main_source_of_drinking_water_Tank_Pond_Lake_Households',
 'Main_source_of_drinking_water_Tapwater_Households',
 'Main_source_of_drinking_water_Tubewell_Borehole_Households',
 'Main_source_of_drinking_water_Un_covered_well_Households',
 'Male_SC',
 'Male_ST',
 'Male_Workers',
 'Male_y',
 'Marginal_Workers',
 'Married_couples_1_Households',
 'Married_couples_2_Households',
 'Married_couples_3_Households',
 'Married_couples_3_or_more_Households',
 'Married_couples_4_Households',
 'Married_couples_5__Households',
 'Married_couples_None_Households',
 'Middle_Education',
 'Muslims',
 'Non_Workers',
 'Not_having_bathing_facility_within_the_premises_Total_Households',
 'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households',
 'Other_Education',
 'Other_Workers',
 'Others_Religions',
 'Ownership_Owned_Households',
 'Ownership_Rented_Households',
 'Population_y',
 'Power_Parity_Above_Rs_545000',
 'Power_Parity_Less_than_Rs_45000',
 'Power_Parity_Rs_150000_240000',
 'Power_Parity_Rs_150000_330000',
 'Power_Parity_Rs_240000_330000',
 'Power_Parity_Rs_330000_425000',
 'Power_Parity_Rs_330000_545000',
 'Power_Parity_Rs_425000_545000',
 'Power_Parity_Rs_45000_150000',
 'Power_Parity_Rs_45000_90000',
 'Power_Parity_Rs_90000_150000',
 'Primary_Education',
 'Religion_Not_Stated',
 'Rural_Households',
 'ST',
 'Secondary_Education',
 'Sikhs',
 'Total_Education',
 'Total_Power_Parity',
 'Type_of_bathing_facility_Enclosure_without_roof_Households',
 'Type_of_fuel_used_for_cooking_Any_other_Households',
 'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households',
 'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households',
 'Type_of_latrine_facility_Other_latrine_Households',
 'Type_of_latrine_facility_Pit_latrine_Households',
 'Urban_Households',
 'Workers',
 'literacy_rate',
 'sex_ratio']

In [50]:
import pandas as pd

# Load files
latlong = pd.read_csv("district wise centroids.csv")
census = pd.read_csv("india-districts-census-2011.csv")

# Merge on District (left = latlong, right = census)
final_df = latlong.merge(
    census,
    left_on="District",
    right_on="District name",
    how="inner"
)

# Derived columns
final_df["sex_ratio"] = round((final_df["Female"] / final_df["Male"]) * 100, 2)
final_df["literacy_rate"] = round((final_df["Literate"] / final_df["Population"]) * 100, 2)

# Keep useful columns
columns_needed = [
    "State", "District", "Latitude", "Longitude",
    "Population", "Male", "Female", "Literate",
    "sex_ratio", "literacy_rate"
]
final_df = final_df[columns_needed]

# Save to CSV for Streamlit
final_df.to_csv("Final india.csv", index=False)

print("Final india.csv saved!")

Final india.csv saved!